import { CustomMission, CustomMissionStep } from '../types';

/**
 * Converts a CustomMission object into a clean, beautifully formatted Markdown string
 * that can be pasted directly into Notion (or saved as a .md file).
 * Notion automatically converts headers, callouts, and `- [ ]` into native blocks.
 */
export function exportMissionToMarkdown(mission: CustomMission): string {
  const stars = Array.from({ length: mission.difficultyStars }).map(() => '★').join('');
  const tags = mission.subjectTags.map(t => `#${t.replace(/\s+/g, '')}`).join(' ');
  const skills = mission.skillsLearned.map(s => `\`${s}\``).join(', ');

  let md = `# 📸 Mission: ${mission.title}\n\n`;
  md += `> **Expedition:** ${mission.expeditionName} | **Difficulty:** ${stars} (${mission.difficultyStars}/5) | **Time:** ⏱️ ${mission.estimatedTime}\n\n`;
  md += `**Tags:** ${tags}\n`;
  md += `**Skills Focused:** ${skills}\n\n`;

  md += `--- \n\n`;
  md += `## 🎯 Mission Objective\n${mission.objective}\n\n`;
  md += `## 💡 Why This Matters\n${mission.whyThisMatters}\n\n`;

  md += `## 🎒 Gear & Setup Requirements\n`;
  md += `- **Gear Needed:** ${mission.gearNeeded}\n`;
  md += `- **Camera Setup:** ${mission.cameraSetup}\n`;
  if (mission.flashSetup) {
    md += `- **Flash & Lighting:** ${mission.flashSetup}\n`;
  }
  md += `- **Subject Concept:** ${mission.subjectConcept}\n\n`;

  if (mission.steps && mission.steps.length > 0) {
    md += `## 📋 Action Steps & Field Checklist\n`;
    mission.steps.forEach((step: CustomMissionStep, index: number) => {
      md += `- [ ] **Step ${index + 1}: ${step.title}**\n`;
      md += `  - ${step.instruction}\n`;
      if (step.tryValues) {
        md += `  - ⚙️ *Try settings:* \`${step.tryValues}\` \n`;
      }
      if (step.watchFor) {
        md += `  - ⚠️ *Watch out for:* ${step.watchFor}\n`;
      }
    });
    md += `\n`;
  }

  if (mission.versionA || mission.versionB) {
    md += `## 🔄 Creative Shot Variations\n\n`;
    if (mission.versionA) {
      md += `### Version A: ${mission.versionA.title}\n`;
      md += `${mission.versionA.description}\n`;
      mission.versionA.bulletPoints?.forEach(bp => {
        md += `- ${bp}\n`;
      });
      md += `\n`;
    }
    if (mission.versionB) {
      md += `### Version B: ${mission.versionB.title}\n`;
      md += `${mission.versionB.description}\n`;
      mission.versionB.bulletPoints?.forEach(bp => {
        md += `- ${bp}\n`;
      });
      md += `\n`;
    }
  }

  if (mission.fieldNotes && mission.fieldNotes.length > 0) {
    md += `## 📝 Professor Field Notes\n`;
    mission.fieldNotes.forEach(note => {
      md += `- ${note}\n`;
    });
    md += `\n`;
  }

  if (mission.technicalCornerTitle && mission.technicalCornerText) {
    md += `> **Technical Corner: ${mission.technicalCornerTitle}**\n`;
    md += `> ${mission.technicalCornerText}\n\n`;
  }

  md += `---\n*Generated by Photo Journey App*`;
  return md;
}

/**
 * Escapes a cell string for RFC 4180 CSV compliance
 */
function escapeCSVCell(str: string | number | undefined | null): string {
  if (str === undefined || str === null) return '""';
  const val = String(str).replace(/"/g, '""');
  return `"${val}"`;
}

/**
 * Converts a list of CustomMissions to a CSV format ready for Notion import
 */
export function exportMissionsToCSV(missions: CustomMission[]): string {
  const headers = [
    'Title',
    'Expedition Name',
    'Estimated Time',
    'Difficulty Stars',
    'Subject Tags',
    'Skills Learned',
    'Objective',
    'Why This Matters',
    'Gear Needed',
    'Camera Setup',
    'Flash Setup',
    'Subject Concept',
    'Steps Count',
    'Technical Corner Title',
    'Technical Corner Text',
    'Created At'
  ];

  let csv = headers.map(escapeCSVCell).join(',') + '\n';

  missions.forEach(m => {
    const row = [
      m.title,
      m.expeditionName,
      m.estimatedTime,
      m.difficultyStars,
      (m.subjectTags || []).join('; '),
      (m.skillsLearned || []).join('; '),
      m.objective,
      m.whyThisMatters,
      m.gearNeeded,
      m.cameraSetup,
      m.flashSetup || '',
      m.subjectConcept,
      (m.steps || []).length,
      m.technicalCornerTitle || '',
      m.technicalCornerText || '',
      m.createdAt || new Date().toISOString()
    ];
    csv += row.map(escapeCSVCell).join(',') + '\n';
  });

  return csv;
}

/**
 * Simple CSV parser for Notion exported or user-supplied CSV files
 */
export function importMissionsFromCSV(csvText: string): CustomMission[] {
  const lines: string[] = [];
  let currentLine = '';
  let insideQuotes = false;

  for (let i = 0; i < csvText.length; i++) {
    const char = csvText[i];
    if (char === '"') {
      insideQuotes = !insideQuotes;
      currentLine += char;
    } else if ((char === '\n' || char === '\r') && !insideQuotes) {
      if (char === '\r' && csvText[i + 1] === '\n') {
        i++; // skip \n
      }
      if (currentLine.trim().length > 0) {
        lines.push(currentLine);
      }
      currentLine = '';
    } else {
      currentLine += char;
    }
  }
  if (currentLine.trim().length > 0) {
    lines.push(currentLine);
  }

  if (lines.length < 2) return [];

  const parseRow = (line: string): string[] => {
    const cells: string[] = [];
    let currentCell = '';
    let inQuote = false;

    for (let i = 0; i < line.length; i++) {
      const c = line[i];
      if (c === '"') {
        if (inQuote && line[i + 1] === '"') {
          currentCell += '"';
          i++;
        } else {
          inQuote = !inQuote;
        }
      } else if (c === ',' && !inQuote) {
        cells.push(currentCell.trim());
        currentCell = '';
      } else {
        currentCell += c;
      }
    }
    cells.push(currentCell.trim());
    return cells;
  };

  const headers = parseRow(lines[0]).map(h => h.toLowerCase());
  const findIndex = (name: string) => headers.findIndex(h => h.includes(name.toLowerCase()));

  const titleIdx = findIndex('title');
  const expIdx = findIndex('expedition');
  const timeIdx = findIndex('time');
  const diffIdx = findIndex('difficulty');
  const tagsIdx = findIndex('tags');
  const objIdx = findIndex('objective');
  const gearIdx = findIndex('gear');

  const missions: CustomMission[] = [];

  for (let l = 1; l < lines.length; l++) {
    const cells = parseRow(lines[l]);
    if (cells.length === 0) continue;

    const title = titleIdx !== -1 && cells[titleIdx] ? cells[titleIdx] : `Imported Mission ${l}`;
    const expeditionName = expIdx !== -1 && cells[expIdx] ? cells[expIdx] : 'Imported';
    const estimatedTime = timeIdx !== -1 && cells[timeIdx] ? cells[timeIdx] : '45 mins';
    const difficultyStars = diffIdx !== -1 ? parseInt(cells[diffIdx], 10) || 3 : 3;
    const subjectTags = tagsIdx !== -1 && cells[tagsIdx] ? cells[tagsIdx].split(/[;,]/).map(t => t.trim()) : ['imported'];
    const objective = objIdx !== -1 && cells[objIdx] ? cells[objIdx] : 'Complete outdoor photo mission';
    const gearNeeded = gearIdx !== -1 && cells[gearIdx] ? cells[gearIdx] : 'Standard Camera';

    const mission: CustomMission = {
      id: `imported-notion-${Date.now()}-${l}`,
      title,
      expeditionName,
      estimatedTime,
      difficultyStars,
      subjectTags,
      skillsLearned: ['Composition', 'Field Practice'],
      objective,
      whyThisMatters: 'Imported mission from Notion for mobile field tracking.',
      gearNeeded,
      cameraSetup: 'Standard shooting mode with appropriate exposure',
      flashSetup: 'Natural light or flash as needed',
      subjectConcept: 'Outdoor field subject',
      steps: [
        {
          title: 'Preparation & Gear Check',
          instruction: 'Verify camera battery, clean lens, and set initial exposure parameters.'
        },
        {
          title: 'Capture & Composition',
          instruction: 'Take multiple angles paying close attention to framing and focus.'
        }
      ],
      versionA: {
        title: 'Primary Shot',
        description: 'Standard composition following baseline rules.',
        bulletPoints: ['Focus on sharp subject', 'Check histogram']
      },
      versionB: {
        title: 'Creative Angle',
        description: 'Experiment with low or high perspective.',
        bulletPoints: ['Try wide aperture', 'Look for reflection or leading lines']
      },
      fieldNotes: ['Imported from Notion mission tracker.'],
      technicalCornerTitle: 'Field Tip',
      technicalCornerText: 'Keep track of key exposure settings on your mobile device while shooting.',
      createdAt: new Date().toISOString()
    };

    missions.push(mission);
  }

  return missions;
}

/**
 * Downloads a string as a file in browser
 */
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Copies text to system clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    } else {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      return true;
    }
  } catch (e) {
    console.error('Clipboard copy failed', e);
    return false;
  }
}

/**
 * Sample CSV Template formatted for Notion Database creation
 */
export const SAMPLE_NOTION_CSV_TEMPLATE = `"Title","Expedition Name","Estimated Time","Difficulty Stars","Subject Tags","Skills Learned","Objective","Why This Matters","Gear Needed","Camera Setup","Flash Setup","Subject Concept"
"Macro Water Drop Magic","Macro Explorations","45 mins",4,"macro; water; indoor","Focus Stacking; Depth of Field","Capture high speed water droplet with crisp reflections","Master high shutter speed & flash timing","Macro lens, Tripod, Speedlight","Manual 1/250s f/11 ISO 100","Off-camera flash 1/32 power","Droplet splash"
"Golden Hour Architecture","Urban & Architecture","60 mins",3,"city; architecture; golden hour","Perspective; Leading Lines","Frame historic building against warm twilight sky","Learn light direction and line control","Wide Angle Lens, Tripod","Aperture Priority f/8 ISO 100","None","Historic facade"`;
